/**
 * @file Automatically generated by barrelsby.
 */

export * from './lib/education.component';
export * from './lib/experience.component';
export * from './lib/projects.component';
export * from './lib/skills.component';
