/**
 * @file Automatically generated by barrelsby.
 */

export * from './lib/about.component';
export * from './lib/hero.component';
export * from './lib/personas.component';
export * from './lib/promo.component';
