/**
 * @file Automatically generated by barrelsby.
 */

export * from './lib/article.interface';
export * from './lib/dictionary.interface';
export * from './lib/hero.interface';
export * from './lib/link.interface';
